
import './wallet'
// import './contract/faucet-contract'
// import './contract/multicall'
// import './contract/token'
// import './contract/pair-contract'
import './swap'
// import './faucet'
import './wallet-connect'
import './liquidity'
